#import "template.typ": *
#import "@preview/wordometer:0.1.4": word-count, total-words
#import "authors.typ": *
//#show: doc => style(doc)

#let title = "Projecting the spatial rewiring of the bumble bee pollination network of the Southern Rocky Mountains"
#let abstract = "Plant-pollinator interaction networks are important. IPBES pollintation report says mapping pollination is essential to address knowledge gaps in this system"

#import "./appendices/a0.typ": appendix-content

#showtitle(title)
#showauthors(authors, institutions, corresponding_email)
#showabstract(abstract)
#show: word-count.with(exclude: (figure, bibliography))
#set heading(numbering: "1.")
#show figure.caption: set align(left)
#show heading: it => {
  [#it]
  v(0em)
}
#show heading.where(level: 3): it =>[
    #block(text(it.body, style: "italic"))
]
#show cite: set text(fill: rgb("#528fd1"))

\
*Word Count*: #total-words
\

_Ecology Letters: 5000 words, 6 figures._

= Introduction

The vast majority of flowering plant species are pollinated by animals @Ollerton2011HowMan. Pollination interactions are essential to plant reproduction and to the maintenance of Earth’s biodiversity @Bascompte2007PlaMut, yet they are increasingly disrupted by climate and land use change. These forces threaten the structure and functioning of pollination networks @Kearns1998EndMut, as well as the biodiversity and ecosystem services that depend on them, which have been well documented across the globe @Potts2016AssessmentReport. Understanding and predicting how plant-pollinator networks respond to anthropogenic change is a central challenge in pollinator ecology @Mayer2011PolEco and conservation biology @Kearns1998EndMut @Gilman2010FrameworkCommunity, with direct relevance for climate adaptation and food security @Bailes2015HowCana @Klein2006ImpPol.

Alpine ecosystems face a unique combination of threats in this context. As temperatures rise, many plant and pollinator species see their suitable habitat shifting upward along elevational gradients  @Hoiss2015IntEff @Richman2020AsyRan. These shifts can reduce the total amount of climatically viable habitat and tend to particularly threaten high elevation species @Rumpf2018RanDyn. Simulatenously, species phenologies are changing in response to warming and earlier snowmelt @Inouye2020EffectsClimate @Steltzer2009BiologicalConsequences, creating the potential for mismatches in flowering and pollinator activity @Memmott2007GloWar @CaraDonna2014ShiFlo @Ogilvie2017IntBee. While phenological mismatches have received substantial attention, they represent only one component of climate driven disruption. A critical, but less explored challenge is the potential for spatial mismatch among species @Polce2014ClimatedrivenSpatial @Hegland2009HowDoes. As ranges shift, some plant and pollinators may cease to overlap in space, while others co-occur for the first time, producing network rewiring across space. Forecasting how range shifts will reshape communities is crucial for informing conservation decisions @Bates2025PredictionsFuture. Interactions are a crucial component of how climate warming will impact range dynamics @HilleRisLambers2013HowWill, but we cannot adaquetely account for their role in range shifts without clear understanding of the spatial structure of networks.

A major challenge here is that species interactions intrinsically vary in space and time @Poisot2015SpeWhy --- in addition to systematic phenological shifts, there is intrinsic year-to-year variation in the structure of empirical pollination networks @Alarcon2008YeaVar. Therefore we need a spatiotemporally explicit approach to understand the present composition of interaction networks and how they are changing @Strydom2021RoaPre. Forecasting the rewiring of networks as their species shift under different climate projections (and understanding how this rewiring affects ecosystem functioning, persistence, and the services ecosystems provide to people) is crucial to conservation strategies designed for uncertain climate futures, and the International Panel on Biodiversity and Ecosystem Services (IPBES) report on pollination identifies mapping pollinator systems as a necessary step toward addressing our gaps in knowledge @Potts2016AssessmentReport. However, spatially explicit predictions of network composition and remain rare because thorough spatial coverage of network composition and structure is very labor intensive @Strydom2021RoaPre. Despite this challenge, recent work has made progress toward integrating the Grinellian and Eltonian niches together @Gravel2019BriElt, enabling spatially explicit network predictions by combining a regional metaweb (all possible interactions across the regional species pool) with species distribution models to predict host composition across space @Dansereau2024SpatiallyExplicit. 

Here, we extend this framework to generate spatially explicit predictions of plant-pollinator network structure across the Southern Rocky Mountains and, crucially, to project how this structure will change over the rest of the 21st-century under potential climate scenarios. We use interaction data from 13 bumble bee species (_Bombus spp._), which have displayed particular sensitivity to climate warming across the globe @Kerr2015ClimateChange, and 157 angiosperm species to construct a regional metaweb composed of 697 known plant-pollinator interactions. We integrate this data with species distribution models to (1) produce spatiotemporally explicit predictions of the bumble bee and wildflower pollination network composition across the southern Rocky Mountains, and (2) identify where and when known interactions are likely to be lost under different climate scenarios. We find consistent upward elevational shifts in suitable habitat and substantial network rewiring across all scenarios, and large reduction in overlap between interacting species in stronger warming scenarios, albeit with considerable variation across species in the extent to which they gain or lose overlap with pollination partners. By quantifying the "vertical disassembly" of these networks, these projections provide a predictive baseline for monitoring change and can guide monitoring and conservation strategies.

= Methods 


#figure(
  image("../plots/concept.svg"),
  caption: [Concept figure depicting the methodology used to quantify the spatial rewiring of the plant-pollinator network. Top: the different data sources used in the framework: in-situ interaction surveys at three sites (Elk Meadows, Rocky Mountain Biological Laboratory, and Pikes Peak) are aggregated into a regional metaweb, occurrence data from GBIF, and bioclimatic variable baselines and projections from WorldClim. These data are then used to project baseline and future species distribution, and then the area of range overlap for each pair of interacting species in the metaweb are used to quantify network rewiring by measuring the projected range area in the future relative to the baseline.]
) <concept>


== Data 

=== Interaction Data

The primary data source for this study is interaction data collected across three different sites in the southern Rocky Mountains of Colorado across a total of 13 _Bombus_ species and 157 flowering plants. The three sample sites are henceforth referred to as Rocky Mountain Biological Lab (RMBL), Pikes Peak, and the University of Colorado Mountain Research Station (MRS) (each marked in @concept, upper left). Observations of bumble bee-plant interactions at the RMBL take place within a long-term bumble bee monitoring project  @Ogilvie2022ShiftingImportance. In brief, at six permanent study sites near the RMBL, bumble bee interactions with flowering plants are monitored for one hour at weekly intervals for the entire growing season (May–September). At these same weekly intervals, floral abundances of all flowering plant species visited by bumble bees is surveyed within a series of 15 permanent 20 x 0.5 m transects at each site. Observations of bees, their interactions with flowers, and counts of flowers take place within the three dominant habitat types where bumble bee activity is observed: wet meadows, dry meadows, and aspen forest. We used seven years (2015-2021) of observational data on Bombus visits to flowering plants at these study sites to aggregate interaction networks. The Pikes Peak data consists of three seasons (2019-2021) of interaction data collected along an elevational gradient ranging from the near the summit of Pikes Peak (4285 m) to down near the transition of the Great Plains (1872 m), sampled roughly twice a week (described in #cite(<Barthell2025BumbleBee>, form: "prose")). MRS data consists of seven seasons (2015-2021) of data at a six plot at 2900 meters elevation, sampled weekly over the entire flowering season (described in #cite(<Resasco2021PlaPol>, form: "prose")).

The metaweb is then constructed by aggregating every interaction seen across all field sites and years, to form the regional network of all known interactions across the southern Rocky Mountains. 

=== Occurrence Data

Occurrence data for each species was curated from GBIF within the region of study. The dataset of all occurrence records can be found at #text(fill: blue)[#link("https://doi.org/10.15468/dl.45er9p", "here")]. Each occurrence record is associated with a geospatial coordinate and a timestamp. The GBIF dataset consists of 181,613 occurrences from iNaturalist research grade observations within the bounding box seen in the top left of @concept (109.7-101.8º West, 34.5-42.5º North).

=== Climate Data

WorldClim @Fick2017Worldclim2 provides 19 bioclimatic variables under a baseline climate at 1$"km"^2$  resolution across Earth’s surfaces. WorldClim also provides these same variables projected into the future until the end of this century in intervals of 20 year averages (2021-2040, 2041-2060, etc.) under different climate scenarios derived from different Earth System Models (ESMs). These projections of bioclimatic variables, and the climate projections they are built on, rely on the framework of Shared-Socioeconomic-Pathways @ONeill2014NewSce to describe different scenarios in how humanity responds to climate change. These scenarios of climate response vary on two axes: mitigation (i.e. by reducing and eventually reaching net-zero greenhouse gas emissions) and adaptation to climate change (i.e. building infrastructure for a warmer world). 

We consider three climate scenarios: SSP1-2.6, SSP2-4.5, SSP3-7.0, representing low, moderate, and extreme warming, respectively. #note("michael", "ask tim about evidence for ssp245 being what we are on track for"). Projections for the global climate for each of these situations are derived from eleven different Earth System Models (ESMs) --- ACCESS-CM2 @Bi2020ConfigurationSpinup, BCC-CSM2-MR @Xin2018BccBcccsm2mr, CMCC-ESM2 @Lovato2022Cmip6Simulations, EC-Earth3-Veg @Doscher2022Ecearth3Earth, GISS-E2-1-G @Kelley2020Gisse21Configurations, INM-CM5-0 @Volodin2017SimulationPresentday, IPSL-CM6A-LR @Boucher2020PresentationEvaluation, MIROC6 @Tatebe2019DescriptionBasic, MPI-ESM1-2-HR @Muller2018HigherresolutionVersion, MRI-ESM2-0 @Yukimoto2019MeteorologicalResearch, and UKESM1_0_LL @Good2019MohcUkesm10ll --- which are then translated into bioclimatic variable predictions by WorldClim.

== Species Distribution Models 

Species distributions are constructed using occurrence data from GBIF using the packages SpeciesDistributionToolkit.jl @Poisot2025JuliaToolkit and EvoTrees.jl @Desgagne-Bouchard2025EvovestEvotreesjl in the Julia language. The 19 baseline bioclimatic variables from WorldClim @Fick2017Worldclim2 used as environmental predictors. For each species, pseudoabsences are generated using "background thickening” @Vollering2019BunchingBackground, where points are selected in proportion to their minimum distance to an observed prsences, with no pseudoabsences allowed within a buffer of any GBIF occurrence record for that particular species. The size of the buffer for each species was selected via hyperparameter optimization (see following paragraph). To infer the spatial distribution of each species, we used EvoTrees.jl to fit Boosted Regression Trees (BRT) with a Gaussian loss metric. The use of a Gaussian loss metric means each node in the classification tree is fit to a Gaussian distribution via maximum-likelihood estimation, and therefore after fitting there is an explicit variance around each split in each tree. Hence, a total uncertainty value associated with each pixel can be constructed by aggregating the variance at each in the classification tree. 

SDMs were evaluated using 5-fold crossvalidation. Performance metrics were computed only on the out-of-fold predictions for each data point. Many metrics have been proposed for evaluating species distribution models --- here we use Matthew's Correlation Coefficient (MCC) as an assessment of SDM performance and comparison,
and perform the final thresholding of the model by selecting the value that maximizes informedness following the arguments made by #cite(<Poisot2023GuiPre>, form: "prose"), #cite(<Delgado2019WhyCohens>, form: "prose"), and #cite(<Chicco2021MatthewsCorrelation>, form: "prose").

We optimize the following hyperparameters: the maximum depth of each tree in the BRT (too few results in underfitting, and too many results in overfitting), the ratio of pseudoabsences to total number of presences, and the buffer radius around each presence around which no pseudoabsence is allowed. We do this via grid search, i.e. testing every possible combination of hyperparameter values across a fixed range for each hyperparameter. For the maximum depth of each tree, we test values in the range ${4,6,8,10}$. For the ratio of pseudoabsences to presences, we use the range ${0.5, 1., dots, 2.5, 3}$, and for the pseudoabsence buffer distance (in kilometers) we use the range ${5, 10, dots, 25}$. This results in a total of 120 models fit for each species, and the set of hyperparameters that yields the highest MCC is chosen for the final model fit. This results in a median MCC of 0.935 for bumble bees and 0.957 for plants, indicating excellent fits in general. The distribution of MCC values for both sets of apecies can be found in Supplemental Figure S1. 

After model capacity is assessed using crossvalidation and the best hyperparameters selected via MCC, the final model is fit on the whole dataset, as is best-practice @Hastie2017ElementsStatistical. This final model is then applied to all future climate scenarios. For each climate scenario and time-period, predictions are made with the bioclimatic variables projected by each ESM, which are then averaged to create an overall ensemble prediction for that combination of climate scenario and time-period. These ensemble predictions are then thresholded using the same optimal threshold as used for the baseline range prediction. Predicted baseline ranges for each species are available in Appendix A2, and visualization of projected shifts for each species are in Appendix A3. 


== Rewiring Quantification

In order to quantify the amount of spatial rewiring for each pair of interacting species over the rest of this century, we take the baseline distribution for each interacting bee and plant species and compute the amount of area in which their ranges overlap. Then, for each future time-period and climate change scenario, we measure the area of their range overlap in the same way, and compute the ratio between the overlap in the future and the baseline. Across all pairs of interacting species, this enables us to map hotspots of lost interactions that are rewiring plant-pollinator networks.

= Results
\
We find that species elevational ranges are consistently projected to shift upwards toward higher elevations and that there is considerable network rewiring under all climate scenarios, with much variation in the total change at the end of the century depending on the degree of warming. In extreme warming scenarios, change continues consistently across the century, whereas in the mild warming scenario (SSP 1-2.6), most of the change in the system is concentrated early in the century (2021-2040), and the state remains realtively consistent through until 2100. We find that, like in many ecosystems under climate change, species can be divided into winners and losers --- those that will gain range under warming climate, and those that will lose range size and range overlap with interaction partners over the remainder of the century. In mild warming scenarios, there are roughly equal numbers of winners and losers, but the number of loser species consistently increases under greater warming scenarios. 

The baseline state of species richness and aggregated SDM uncertainty is shown in @richness-uncertainty. Species are primarilly concentrated above 2500m elevation, while uncertainty is fairly evenly distributed across elevation, with a peak around 2300-2500m, where the estimated species richness is changing the most. This is unsurpising as the SDMs are most uncertain around the regions predicted to be at the near the edge of each species' range. These regions of high predicted species richness, but also high uncertainty, provide a priority for targeting for future sampling effort to better estimate the baseline state of species composition across space, which is essential to detect and attribute change @Gonzalez2023FraDet. 

There is also spatial structure to the diversity of richness within each year. In Supplemental Material we estimate species phenologies using Bayesian Gaussian Mixture models and display the phenology-weighted interaction richness across space in Supplemental Figure S2, which shows interation richness moves from being concentrated in the North to the South as the season progresses. Full details of the methodology are in A1.  


#figure(
  image("../plots/richness_vs_uncertainty.png"),
  caption: [Bivariate plot depicting the predicted species richness and the aggregate uncertainty across all species distribution models. Top right: the mean species richness (green) and uncertainty across elevation (after normalizing uncertainty to $[0,1]$). Bottom right: Bar plot showing the proportion of area corresponding with each class in the bivariate legend. Colors accounting for less than 1% of area are omitted.]
) <richness-uncertainty>


== Range Shift Projections

We find species ranges to be consistently projected to increase in elevation across all climate scenarios. The top-left of @range-shift shows the change in the median elevation for each species at each time-period under each climate scenario. Under all scenarios, the expected range shifts for the time-period 2021-2040 are extremely similar, with most species moving between 0-250m in elevation. However, the resulting shifts for the remainder of the century then start to vary depending on climate scenarios. In the mild warming scenario (SSP 1-2.6), there is a slight continued upward shift across all species in 2041-2060, corresponding to an average increase of about 50m, but after 2060 the elevational ranges stay nearly identical. However, in increasingly extreme climate scenarios, ranges continue to move upward in elevation, resulting in more total variation across species. In the extreme climate scenario, SSP 3-7.5, range shifts vary from -200m (meaning 200m down in elevation) to nearly 1000m upward, with a median slightly above 400m. Elevation shifts of this magnitude correspond to a vast change in the availability of oxygen (for bees) and carbon dioxide (for plants), which could be a psysiological limitation not accounted for in bioclimatic variables. 

The right panels of @range-shift show the spatial distribution of species range gains (blues) and losses (reds) in the middle-of-the-road climate scenario (SSP 2-4.5). The biggest species losses are in the so-called Front Range (the region where the plains of eastern Colorado meet the foothills of the rockies), and the most gain is in the northwest, home to arid high-elevation plains, with the combinations of both high gain and loss among the western and northern foothills. Spatial projections of gained and lost range for each individual species are contained in Appendix 3. 

#figure(
  image("../plots/range_shift.png"),
  caption: [Projected range shifts across different time-periods and climate scenarios. Top-left: The density of the projected shift of the median elevation of each species range in different time-periods (colors) and climate scenarios (columns). The dashed grey line indicateds no change. Right: bivariate plots depicted the projected number of species gained and lost in each time-period in the middle-of-the-road climate scenario (SSP 2-4.5).]
) <range-shift>


== Network Rewiring Projections

By measuring the amount of overlapping area between species ranges of pairs of interacting species, we are able to spatially quantify the degree of network rewiring across space. We map the number of lost interactions across space and find increasing amount and spatial extent of loss under increasingly extreme climate scenarios, concentrated in the foothills. We also find that the median range overlap is expected to decline under all but the most mild climate scenario, with considerable variability in the nature of this rewiring depending if the median is taken across either all plant or all bee species. We also see a common phenomenon when projecting ecosystem change, which is species can be divided into "winners" and "losers", with more species becoming losers in more extreme warming scenarios. 

=== Interaction gain and loss in space

@interaction-loss shows the total number of lost interactions across space at the end of the century under each climate scenario. Interaction loss is primarily concentrated in regions of high species richness, within the elevations of 2400-3200 meters. In more extrema warming scenarios, there is both increase in the number of lost interactions, and a moderate shift upwards in the elevation of peak elevation loss (@interaction-loss, bottom right). Even in the most mild climate scenario, there are still many regions expected to see losses of 100-200 interactions, which represent 15-30% of the total number of interactions in the metaweb. 

In Supplemental Figure S3, we see a plot similar to @interaction-loss, except for the _gained_ interactions across space. The elevation range for gains is higher than losses, with most being gained between 3200-4000 meters. Similarly, more interactions are gained in more extremea warming scenarios, primarily in in the foothills of the southwest and the northwest. However, the total number of interactions gained is far lower than those lost, with at maximum gain of 30-50 interactions at the elevation with the highest gain, depending on climate scenario.   

As species ranges shift, this also results in novel co-occurrences among species that have never been observed together before, so we are unsure if they are capable of interacting. Maps of the number of novel co-occurrences are shown in Supplemental Figure S4, which are primarily concentrated in the eastern foothills and subalpine, and typically are far lower than the number of lost interactions, although in the highest 20% quantile covers a range spanning from 30-200 novel co-occurrences, which are similar across all climate scenarios. 

#figure(
  image("../plots/interaction_loss.png"),
  caption: [The total number of lost interactions at the end of this century for each climate scenario. Each shade of purple represents a 20% quantile of lost interactions in the most extrema scenario, with the cutoffs between quantiles labeled on the color bar. Bottom Right: the mean number of lost interactions at each elevation in each of the climate scenarios (colors). The bar plot in the bottom right of each map is the proportion of area that falls into each quantile. The background (regions in white) have an expected loss of 0 interactions (and in much of this region, there are 0 interactions in the baseline to begin with).] 
) <interaction-loss>


=== Shifting range overlap among interacting species

In @overlap-change\A, we show the density of the relative range overlap for all of the species each bumble bee interacts with in the moderate warming scenario (SSP 2-4.5) across each future time-period. In general we see decline in the median overlap for each bumble bee species, but there is conserable variation across the many plant species each bee interacts with.  

For each species $s$, we compute the range area that overlaps across each species $s$ interacts with, and from those values compute the median, resulting in a single value for each species. We refer to the case where we compute range overlap for each bee species $s$ as the _bee perspective_, and each plant species $s$ as the _plant perspective_. The distribution of the median change in range overlap from both the bee and plant perspectives are shown in @overlap-change\B (right) for each time-period and climate scenario, aggregated for each bee species in the top panel, and each plant species in the bottom panel. For example, this means each data-point in box-and-whisker plots for SSP 2-4.5 in the top panel of @overlap-change\B is derived from the the median value of the density for each bee in the corresponding time-period. 

For both sets of species (bee and plants), we see a very slight increase in overlap during the earliest time-period (2021-2040), with subsequent decrease in overlap for moderate and extreme climate scenarios (SSP 2-4.5 and 3-7.0), and relative stability for the mild warming scenario (SSP 1-2.6). From the bee perspective, in the moderate and extreme warming case, we see a large decline in range overlap, with a 25% decline relative to the baseline by 2100 in SSP 2-4.5, and a 40% decline by the end of the century for bee species in SSP 3-7.0. 

From the plant perspective, there is still a general pattern of decline in moderate and extreme climate scenarios, but there are also a considerable amount of number of plant outlier species, all on the upper end of increasing overlap. This corresponds to species "moving in" to the system at high levels as their range expands into the southern Rocky Mountains. For example, consider the labeled points in @overlap-change\B: _Ipomopsis aggregata_ already has a widespread range, but is projected to make large range gains in the northwest arid plains, along with many bee species (@range-shift)._Taraxacum officinale_, the common dandelion, is naturalized in temperate climates of North America, and expected to gain much range in the western part of the extent in the high-elevation arid grasslands. _Asclepias tuberrosa_ has limited distribution in the Front Range, but is widespread in the southwestern United States, including the south west of the region of interest. It is projected to gain considerable range in the southwestern foothills and at higher elevations in the east. _Asclepias asperula_ is already widespread in the south and expected to move northward. Across time-periods and climate scenarios, the members of the genus _Asclepias_ (milkweeds) in this study, _A. tuberosa_, _A. asperula_, and _A. speciosa_ consistently have the highest overlap relative to baseline.   

Despite the general trend of overlap decline, this variation points to a common feature of many ecosystems under projections of climate change, which is some species end up "winners", and some end up "losers".

#figure(
  image("../plots/overlap_change.png"),
  caption: [(A) Density plots for the relative range overlap size for each plant species a given bee interacts with. Each panel correponds to a future time-period, all under the middle-of-the-road climate scenario (SSP 2-4.5). (B) Box-and-whisker plots depicting the median amount of range overlap for interacting species across different future time-peroids (columns) and climate scenarios (colors), relative to the baseline. The top panel shows bee species, and the bottom shows plant species. In the plant panel, points depict outliers that are more than $1.5R$ from the edge of each box, where $R$ is the inter-quantile range, i.e. the difference between the 75% and 25% quantiles. Images for _A. asperula_ and _A. tuberosa_ are Creative Commons licensed and come from Wikipedia users _Eric Hunt_ and _Lunch_, respectively.]
) <overlap-change>

=== Winning and losing species

We classify species as _relative_ or _absolute_ winners and losers based on species based on changes in both total range area and median spatial overlap with their interaction partners. Absolute winners gain range area and also increase their median overlap with interacting species. Relative winners lose range area but still experience an increase in median overlap. Absolute losers lose both range area and median overlap, while relative losers gain range area but show a decrease in median overlap with interaction partners. @sankey shows the number of winning and losing species across time periods and climate scenarios. There a very few relative losers as  relative range size change and relative overlap are positvely correlated --- the average Spearman correlation across scenarios and time-periods is $rho=0.76$ --- see Supplemental Figure S5.

Notably in @sankey, the number of winners and losers is stable in the mild climate warming scenario, but we see a large increase in absolute loser bees (up to more than half of them) in moderate warming, and still further increase to 10/13 bees as absolute losers at the end of the century under SSP 3-7.0. We see a similar increase under more severe warming scenarios for plants as well, but the increase is less drastic than the jump for bees when shifting from mild to moderate warming. 

#figure(
  image("../plots/sankey.png"),
  caption: [Sankey plots depicting the number of species in each of the winner/loser categories (absolute winner in green, relative winner in blue, absolute loser in orange, and relative loser in purple) across time. Each Sankey plot depicts the four future time periods as columns. Bee species are shown in the top, and plant species in the bottom. The number under each vertical bar corresponds to the number of species in the above category. Each panel column corresponds to a climate scenario.]
) <sankey>


= Discussion 


#note("michael", "papers to read and cite:")
@Hodkinson2005TerrestrialInsects @Inouye2020EffectsClimate @Vitasse2021PhenologicalElevational @Hegland2009HowDoes @Buckley2014ElevationalClines @Shah2020HighElevation 
@Birrell2020InsectsHighelevation  @HilleRisLambers2013HowWill
@Memmott2007GloWar

By combining in-situ interaction data with community science occurrence records and raster projections of bioclimatic variables, we are able to predict the contemporary ranges of the _Bombus_ pollination metaweb, and project the future range shifts of each species, and quantify the degree of spatial rewiring that this network will face over the remainder of the 21st century under different climate scenarios. We found consistent upward elevational range shifts under all scenarios, but with shifts being contained to around 150-250 meters upward by 2021-2040 under SSP 1-2.6, while suitable ranges continued to move further upward over the rest of the century under more extreme warming scenarios. We identified that there the foothills of the southern Rocky Mountains as a hotspot for interaction loss, with nearly an order of magnitude more interactions expected to be lost than gained in the locations with the most extreme change, suggesting vertical disassembly of this network may not be compensated by colonization by new species. The projected decline in median range overlap poses a significant threat to the robustness of these networks. Under both moderate and extreme warming scenarios there is considerable expected decline in the size of median range overlap by the end of the century (30-40% in SSP 3-7.0) from the perspective of both bumble bees and their pollinators. While some species emerge as climate "winners", the proportion of winners declines with increasing amounts of warming.   

It is essential to remember these projections are based on suitability based on bioclimatic variables, which are not, alone, the determinant of future distribution and abundance of species @Thomas2010ClimateClimate. There are numerous factors that are required for species to track their suitable climatic conditions. There are abiotic effects not directly accounted for here: for example the availability of oxygen (for bees) and carbon dioxide (for plants) is not directly considered in bioclimatic variables, and species may have physiological requirements that cannot be met where the climatic conditions of temperature and precipitation are most suitable @Jacobsen2020DilemmaAltitudinal. Additionally, high elevations are subject to more extreme winds, and the potential for frost, which both could damage plants and inhibit their reproduction @Steltzer2009BiologicalConsequences. 

Further, biotic effects also impact the ability of species to track their ranges. It is thought that the relative sparsity of pollinaters at high altitudes plant reproduction in alpine environments @Totland1993PollinationAlpine, although the more intense winds found at higher altitudes can substitute for animal pollination in some species @Totland2001PollenLimitation. There is also the impact of the limited dispersal capacity for some insects --- @Pyke2016EffectsClimate found upward shifts in the same system (bumble bees at RMBL field sites), but not enough to track the average temperature of their range 30 years prior @Pyke1982LocalGeographic. The reshuffling of ranges also will affect interactions besides plant-pollinator mutualisms: competition with newly arriving species has the potential to disrupt existing community structure. Even absent clear competitive advantages for some species, the ability of species to invade (or resist invasion) may be contigent on the order of arrival of species as priority effects are the primary factor in community assembly @Song2021UntanglingComplexity.

Therefore, our results predicting species and interaction richness into the future represent a "best-case" where species are fully capable of tracking their ranges. Rather than treating these as definitive forecasts of plant-pollinator network change, we believe these results provide guidelines for prioritizing further research into what species and particular interactions are expected to undergo the most change, and what the impact of this change on species diversity and persistence will be. For example, these projections identify which and where pairs of species expected to co-occur for the first time, which provides both a list of species to use models to predict if pollination interactions between these species are biologically feasible @Strydom2021RoaPre, but also spatial targets to validate these predicitons. This is essential to meet the guidelines from the International Panel on Biodiversity and Ecosystem Services (IPBES), which highlights mapping pollination as one of the necessary directions for addressing knowledge gaps in our understanding of plant-pollinator systems @Potts2016AssessmentReport.

Experimental conditions are necessary to confidently assess the ecological consequences of projected changes in network composition on species diversity, experimental systems @HilleRisLambers2013HowWill, but the full scope of all possible changes in these systems would prove impractical for rigorous experiment. Therefore the framework presented here can provide projected impacts that can guide these experiments toward testing the consequences of the changes that are most likely to be realized in the real world. Future work on developing mechanistic species distribution models to directly incorporate species physiological limits into range shift projections, but these models are very data hungry and thus benefit from work like this to prioritize data collection on species' physiological response to expected change.


We have demonstrated how species distribution modelling can be combinted with in-situ interaction surveys to generate spatially explicit projections of network structure to map the rewiring of plant-pollinator networks. Developing a spatiotemporally explicit theory of species interaction networks is essential for understanding and mitigating the consequences of climate change on these systems and the services they provide people @Strydom2021RoaPre. In addition to guidance for future experimentation, spatially explicit projections of network composition and change can guide where future monitoring efforts will be most fruitful, such that they can provide the most information possible to detect and attribute change @Gonzalez2023FraDet, and make better decisions to manage and mitigate the negative consequences of this change in these systems @Chapman2023BriAda. This work is essential to guide future long-term monitoring programs of plant-pollinator interactions, which can then collect data for shorter-term forecasts to better enable adaptive management and conservation @Dietze2018IteNea. Together, this would enable a multi-scale synthesis of biogeographic scale prediction of species interaction network composition (as done here) with process-based models of the dynamics of abudance in plant-pollinator communities @Valdovinos2019MutNet, which would serve to aid both conservation and better scientific understanding of the ecology and evolution of plant-pollinator mutualisms, and better mitigate the consequences of plant-pollinator rewiring in a warming world. 

---

*Code and Data Availability*: Github, Zenodo, etc.

*Acknowledgements*:  MDC is funded by an IVADO Postdoctoral Fellowship. TP is funded by an NSERC Discovery grant, a Discovery Acceleration Supplement grant, and a Wellcome Trust grant (223764/Z/21/Z). AG and MDC were supported by the Liber Ero Chair in Conservation. 

// #showbibliography("refs.bib") 
    #bibliography("refs.bib", title: "References", style: "springer-basic-author-date")


