//#import "template.typ": *
//#import "@preview/wordometer:0.1.4": word-count, total-words
#import "authors.typ": *
//#show: doc => style(doc)

#import "preprint.typ": preprint
#show: preprint.with()


= Introduction

As climate and land use change reshuffle the distribution of species on Earth, the networks of species interactions that underpin ecosystem function and persistence are becoming “rewired”, as some interaction partners cease to overlap in space, while others co-occur for the first time. The impacts network rewiring will have on biodiversity will remain largely unknown, largely because the current spatial structure of species interaction networks is not well understood due to the intensive sampling effort documenting interaction networks requires @Jordano2016ChasingEcological @Strydom2021RoadmapPredicting. Despite this challenge, recent work has made progress toward integration of the Grinellian and Eltonian niches  @Gravel2019BringingElton, enabling spatially explicit predictions of interaction network structure by combining a regional metaweb (all possible interactions across the regional species pool) with species distribution models to predict network composition across space @Strydom2021RoadmapPredicting @Dansereau2024SpatiallyExplicit . Extending these predictions into temporal projections of how range shifts will reshape communities is crucial for informing conservation decisions @Bates2025PredictionsFuture. Interactions play a crucial role in determining how climate warming will impact range dynamics @HilleRisLambers2013HowWill, and can shift the structure of competition among species @Barthell2025BumbleBee, but we cannot adequately account for the impact interactions will have in changing communities without a clear understanding of the spatial structure of networks and how it is changing.

A major challenge here is that species interactions intrinsically vary in space and time @Pillai2010PatchdynamicFramework @Poisot2015SpeciesWhy @Trojelsgaard2016EcologicalNetworks — in addition to systematic phenological shifts, there is intrinsic year-to-year variation in empirical networks @Alarcon2008YeartoyearVariation @CaraDonna2021SeeingStatic. Therefore we need a spatiotemporally explicit approach to understand the present composition of interaction networks and how they are changing @Strydom2021RoadmapPredicting. Forecasting network structure as their species shift under different climate projections (and understanding how this rewiring affects ecosystem functioning, persistence, and the services ecosystems provide to people) is crucial to conservation strategies designed for uncertain climate futures. 

In particular, understanding how plant-pollinator networks will shift under different climate scenarios is an imperative, as the vast majority of flowering plant species are pollinated by animals @Ollerton2011HowMany, enabling plant reproduction and the maintenance of Earth’s biodiversity @Bascompte2007PlantanimalMutualistic. Understanding and predicting how plant-pollinator networks respond to anthropogenic change is a central challenge in pollinator ecology @Mayer2011PollinationEcology @Peralta2024PredictingPlant and conservation biology @Kearns1998EndangeredMutualisms @Gilman2010FrameworkCommunity, with direct relevance for climate adaptation and food security @Klein2006ImportancePollinators @Bailes2015HowCan. While phenological mismatches have received substantial attention @Memmott2007GlobalWarming @Ogilvie2017InteractionsBee @Zoller2026PhenologicalShifts @Hegland2009HowDoes @Burkle2013PlantpollinatorInteractions @Rafferty2011EffectsExperimental @Forrest2015PlantPollinator @Gerard2020GlobalWarming @Iler2021DemographicConsequences, the potential for spatial mismatch among species @Hegland2009HowDoes @Polce2014ClimatedrivenSpatial remains less explored. As a result the International Panel on Biodiversity and Ecosystem Services (IPBES) report on pollination identifies spatial mapping as a necessary step toward addressing our gaps in knowledge of pollination systems @Potts2016AssessmentReport. Mountainous ecosystems face a unique combination of threats in this context. As temperatures rise, many plant and pollinator species see their suitable habitat shifting upward along elevational gradients @Hoiss2015InteractiveEffects @Richman2020AsynchronousRange. These shifts can reduce the total amount of climatically viable habitat and tend to particularly threaten high elevation species @Rumpf2018RangeDynamics.

Here, we generate spatially explicit predictions of plant-pollinator network structure across the Southern Rocky Mountains of Colorado and project how this structure will change over the rest of the 21st-century under several potential climate scenarios. We use interaction data from 13 bumble bee species (_Bombus spp._), which have displayed particular sensitivity to climate warming across the globe @Kerr2015ClimateChange @Soroye2020ClimateChange @Hemberger2024WarmingSummer. We construct a regional metaweb composed of 697 known plant-bumble bee interactions among 157 angiosperm species. To determine where and when interaction networks are changing the most, we integrate this data with species distribution models to produce spatiotemporally explicit predictions of the bumble bee and wildflower pollination network composition across the southern Rocky Mountains. Together, this enables us to identify where and when known interactions are likely to be lost under different climate scenarios. From our analyses, we find consistent upward elevational shifts in suitable habitat and substantial network rewiring across all scenarios. These changes stem from a large reduction in overlap between interacting species in stronger warming scenarios, albeit with considerable variation across species in the extent to which they gain or lose overlap with pollination partners. By quantifying the “vertical disassembly” of these networks, these projections provide a predictive baseline for detecting change and can guide monitoring and conservation strategies.


= Methods

We make spatially explicit projections of how plant-pollinator networks will change under different climate scenarios by combining a regional metaweb constructed from field surveys with species distribution models (SDMs) constructed from crowdsourced occurrence records. We then use these SDMs to project species’ distributions under different climate warming scenarios, and use these projections to map hotspots of expected changes in the composition of pollination interaction networks as the ranges of bumble bees and the plants they pollinate shift over the remainder of the century.     



#figure(
  image("../plots/concept.svg"),
  caption: [Concept figure depicting the methodology used to quantify the spatial rewiring of the plant-pollinator network. Top: the different data sources used in the framework: in-situ interaction surveys at three sites (Elk Meadows, Rocky Mountain Biological Laboratory, and Pikes Peak) are aggregated into a regional metaweb, occurrence data from GBIF, and bioclimatic variable baselines and projections from WorldClim. These data are then used to project baseline and future species distribution, and then the area of range overlap for each pair of interacting species in the metaweb are used to quantify network rewiring by measuring the projected range area in the future relative to the baseline.]
) <concept>


== Data 

=== Interaction Data 

The primary data source for this study is from pollination interaction surveys collected across three different sites in the southern Rocky Mountains of Colorado across a total of 13 Bombus species and 157 flowering plants. The three sample sites are henceforth referred to as Rocky Mountain Biological Lab (RMBL), Pikes Peak, and Elk Meadows, near the University of Colorado Mountain Research Station (MRS) (each marked in <concept>, upper left). Observations of bumble bee-plant interactions at the RMBL take place within a long-term bumble bee monitoring project @Ogilvie2022ShiftingImportance. In brief, at six permanent study sites near the RMBL, bumble bee interactions with flowering plants are monitored for one hour at weekly intervals for the entire growing season (May–September). At these same weekly intervals, floral abundances of all flowering plant species visited by bumble bees is surveyed. RMBL data consists of seven years (2015-2021) of surveys on Bombus visits to flowering plants at these study sites. The Pikes Peak data consists of three seasons (2019-2021) of interaction data sampled roughly twice a week (described in #cite(<Barthell2025BumbleBee>, form: "prose")), collected along an elevational gradient ranging from the near the summit of Pikes Peak, a high elevation mountain in south central Colorado (4285 m), to the transition to the North American Great Plains (1872 m) to Pikes Peak’s east. MRS data consists of seven seasons (2015-2021) of data at six plots at 2900 meters elevation, sampled weekly over the entire flowering season (described in #cite(<Resasco2021PlantPollinator>, form: "prose")). 

Every interaction seen across all field sites and years is then aggregated to form the regional metaweb of all known bumble bee pollination interactions across the southern Rocky Mountains.

=== Climate Data 

WorldClim @Fick2017Worldclim2 provides 19 bioclimatic variables under a baseline climate at 1km2 resolution across Earth’s surfaces. WorldClim also provides these same variables projected into the future until the end of this century in intervals of 20 year averages (2021-2040, 2041-2060, etc.) under different climate scenarios derived from different Earth System Models (ESMs). These projections of bioclimatic variables, and the climate projections they are built on, rely on the framework of Shared-Socioeconomic-Pathways (O'Neill et al. 2014) to describe different scenarios in how humanity responds to climate change. These scenarios of climate response vary on two axes: mitigation (i.e. by reducing and eventually reaching net-zero greenhouse gas emissions) and adaptation to climate change (i.e. building infrastructure for a warmer world). 

We consider three climate scenarios: SSP1-2.6, SSP2-4.5, SSP3-7.0, representing low, moderate, and extreme warming, respectively. To best account for uncertainty in how global climate will change in the 21st century, for each climate scenario we use projections derived from eleven different Earth System Models (ESMs) — ACCESS-CM2 @Bi2020ConfigurationSpinup, BCC-CSM2-MR @Xin2018BccBcccsm2mr, CMCC-ESM2 @Lovato2022Cmip6Simulations, EC-Earth3-Veg @Doscher2022Ecearth3Earth, GISS-E2-1-G @Kelley2020Gisse21Configurations, INM-CM5-0 @Volodin2017SimulationPresentday, IPSL-CM6A-LR @Boucher2020PresentationEvaluation, MIROC6 @Tatebe2019DescriptionBasic, MPI-ESM1-2-HR @Muller2018HigherresolutionVersion, MRI-ESM2-0  @Yukimoto2019MeteorologicalResearch, and UKESM1_0_LL @Good2019MohcUkesm10ll — which are then translated into bioclimatic variable predictions by WorldClim.

== Species Distribution Models

Species distributions were modeled using occurrence data from GBIF using the packages SpeciesDistributionToolkit.jl @Poisot2025JuliaToolkit and EvoTrees.jl @Desgagne-Bouchard2025EvovestEvotreesjl in the Julia programming language. The 19 baseline bioclimatic variables from WorldClim 2.1 @Fick2017Worldclim2 were used as environmental predictors. For each species, pseudoabsences are generated using “background thickening” @Vollering2019BunchingBackground, where points are selected in proportion to their minimum distance to an observed presences, with no pseudoabsences allowed within a buffer of any GBIF occurrence record for that particular species. Both the number of pseudo absences, and the size of the buffer, were treated as a hyperparameter that is optimized to find the best fitting model for each species, as described further below. To infer the spatial distribution of each species, we used EvoTrees.jl to fit Boosted Regression Trees (BRT) with a Gaussian loss metric. The use of a Gaussian loss metric means each node in the tree is fit to a Gaussian distribution via maximum-likelihood estimation, and therefore a total uncertainty value associated with each pixel in the SDM can be constructed by aggregating the variance at each node in the classification tree.

SDMs were evaluated using 5-fold crossvalidation. Performance metrics were computed only on the out-of-fold predictions for each data point. Many metrics have been proposed for evaluating species distribution models. Here we use Matthew’s Correlation Coefficient (MCC) as an assessment of SDM performance and comparison (as it ascribes more equal importance to both true positives and true negatives than alternatives, see #cite(<Chicco2021MatthewsCorrelation>, form:"prose") for more details), and perform the final thresholding of the model by selecting the value that maximizes informedness (also known as the true-skill statistic, or Youden’s J) following the recommendations made by #cite(<Poisot2023GuidelinesPrediction>, form:"prose"), #cite(<Delgado2019WhyCohens>, form:"prose"), and #cite(<Chicco2021MatthewsCorrelation>, form:"prose").

For each model, the number of true-positives ($"tp"$), false-positives ($"fp"$), true-negatives ($"tn"$), and false-negatives ($"fn"$) is computed on the out-of-fold predictions, which are then used to compute MCC as 

$
  "MCC" = ("tp" dot "tn" - "fn" dot "fp") / sqrt(("tp" + "fp")("tp" + "fn")("tn" + "fp")("tn"+"fn"))
$

and Informedness $cal(I)$ as 

$
  cal(I) = ("tp") / ("tp" + "fn") + ("tn")/("tn" + "fp") - 1
$

We optimize the following hyperparameters: the maximum depth of each tree in the BRT (too few results in underfitting, and too many results in overfitting), the ratio of pseudoabsences to total number of presences, and the buffer radius around each presence around which no pseudoabsence is allowed. We do this via grid search, i.e. testing every possible combination of hyperparameter values across a fixed range for each hyperparameter. For the maximum depth of each tree, we test values in the range ${4, 6, 8, 10}$. For the ratio of pseudoabsences to presences, we use the range ${0.5, 1, ... , 2.5, 3}$, and for the pseudoabsence buffer distance (in kilometers) we use the range ${5, 10, ..., 25}$. This results in a total of 120 models fit for each species, and the set of hyperparameters that yields the highest MCC is chosen for the final model fit. This results in a median MCC of 0.935 for bumble bees and 0.957 for plants, indicating excellent fits in general. The distribution of MCC values for both sets of species can be found in Supplemental Figure S1.

After model capacity is assessed using crossvalidation and the best hyperparameters selected via MCC, the final model is fit on the whole dataset, as is best-practice @Hastie2017ElementsStatistical. This final model is then applied to all future climate scenarios. For each climate scenario and time-period, predictions are made with the bioclimatic variables projected by each ESM, which are then averaged to create an overall ensemble prediction for that combination of climate scenario and time-period. 

These ensemble predictions are then thresholded using the same optimal threshold as used for the baseline range prediction. Predicted baseline ranges for each species are available in Appendix A2, and visualization of projected shifts for each species are in Appendix A3.

== Spatial Rewiring Quantification

In order to quantify the amount of spatial rewiring (species leaving and entering the local network at a given location)  for each pair of interacting species over the rest of this century, we take the baseline distribution for each interacting bee and plant species and compute the amount of area where their ranges overlap. Then, for each future time-period and climate change scenario, we measure the area of their range overlap in the same way, and compute the ratio between the overlap in the future and the baseline. We also compute the number of interaction pairs that are gained and lost at each pixel, enabling us to map hotspots of change.

= Results

Our results project species elevational ranges are consistently projected to shift upwards toward higher elevations, with much variation in the total change at the end of the century depending on the degree of warming. These shifts then lead to widespread hotspots of spatial rewiring (species being both lost and gained in local networks) across the southern Rocky Mountains, with loss of species interactions concentrated in the foothills. 

In extreme warming scenarios, change continues consistently across the century, whereas in the mild warming scenario (SSP 1-2.6), most of the change in the system is concentrated early in the century (2021-2040), and the state remains relatively consistent through until 2100. We find that, like in many ecosystems under climate change, species can be divided into winners and losers — those that will gain range under warming climate, and those that will lose range size and range overlap with interaction partners over the remainder of the century. In mild warming scenarios, there are roughly equal numbers of winners and losers, but the number of loser species consistently increases under greater warming scenarios.

== Baseline spatial structure of the plant-pollinator network

The baseline state of species richness and aggregated SDM uncertainty is shown in @richness-uncertainty. Species are primarily concentrated above 2500 meters in elevation, while uncertainty is fairly evenly distributed across elevation, with a peak around 2300-2500m, where the estimated species richness is changing the most. This is unsurprising as the SDMs are most uncertain around the regions predicted to be near the edge of each species’ range. These regions of high predicted species richness, but also high uncertainty, provide a priority for targeting for future sampling effort to better estimate the baseline state of species composition across space, which is essential to detect and attribute change @Gonzalez2023FrameworkDetection.

#figure(
  image("../plots/richness_vs_uncertainty.png"),
  caption: [Bivariate plot depicting the predicted species richness and the aggregate uncertainty across all species distribution models. _Top right_: the mean species richness (green) and uncertainty across elevation (after normalizing uncertainty to $[0,1]$). _Bottom right_: Bar plot showing the proportion of area corresponding with each class in the bivariate legend. Colors accounting for less than 1% of area are omitted.]
) <richness-uncertainty>

== Range Shift Projections

We find species ranges are consistently projected to increase in elevation across all climate scenarios. The top-left of Figure 3 shows the change in the median elevation for each species at each time-period under each climate scenario. Under all scenarios, the expected range shifts for the time-period 2021-2040 are extremely similar, with most species moving between 0-250 meters in elevation. However, the change in the remainder of the century then depends on the climate pathway taken. In the mild warming scenario (SSP 1-2.6) there is a slight continued upward shift across all species in 2041-2060, corresponding to an average increase of about 50 meters, but after 2060 the elevational ranges stay nearly identical. However, in increasingly extreme climate scenarios, ranges continue to move upward in elevation, resulting in more total variation across species. In the extreme climate scenario, SSP 3-7.0, range shifts vary from −200 meters (meaning 200 meters down in elevation) to nearly 1000 meters upward, with a median slightly above 400 meters. Elevation shifts of this magnitude correspond to a vast change in physiological constraints, namely the availability of oxygen (for bees) and carbon dioxide (for plants), which could be a limitation on the ability of species to track their climatic niche not accounted for in bioclimatic variables.

The right panels of Figure 3 show the spatial distribution of species range gains (blues) and losses (reds) in the middle-of-the-road climate scenario (SSP 2-4.5). The biggest species losses are in the so-called Front Range (the region where the plains of eastern Colorado meet the foothills of the rockies), and the most gain is in the northwest, home to arid high-elevation plains, with the combinations of both high gain and loss among the western and northern foothills. Spatial projections of gained and lost range for each individual species are contained in the supplemental material.

#figure(
  image("../plots/range_shift.png"),
  caption: [Projected range shifts across different time-periods and climate scenarios. _Top-left_: The density of the projected shift of the median elevation of each species range in different time-periods (colors) and climate scenarios (columns). The dashed grey line indicates no change. _Right_: bivariate plots depicted the projected number of species gained and lost in each time-period in the middle-of-the-road climate scenario (SSP 2-4.5).]
) <range-shift>


== Network Rewiring Projections

By measuring the amount of overlapping area between species ranges of pairs of interacting species, we are able to spatially quantify the degree of network rewiring across space. We map the number of lost interactions across space and find increasing levels of loss under increasingly extreme climate scenarios, concentrated in the montane region (2500-3000m elevation). We also find that the median range overlap is expected to decline under all but the most mild climate scenario, with considerable variability depending if the median is taken across either all plant or all bee species. We also see a common phenomenon when projecting ecosystem change, where species can be divided into “winners” and “losers”, with more species becoming losers in more extreme warming scenarios.

=== Interaction gain and loss in space 

@interaction-loss shows the total number of lost interactions across space at the end of the century under each climate scenario. Interaction loss is primarily concentrated in regions of high species richness, within the elevations of 2400-3200 meters. In more extreme warming scenarios, there is both an increase in the number of lost interactions, and a moderate shift upwards in the elevation of peak elevation loss (@interaction-loss, bottom right). Even in the most mild climate scenario, there are still many regions expected to see losses of 100-200 interactions.

In Supplemental Figure S3, we see a plot similar to @interaction-loss, except for the gained interactions across space. The elevation range for gains is higher than losses, with most being gained between 3200-4000 meters. Similarly, more interactions are gained in more extreme warming scenarios, primarily in the foothills of the southwest and the northwest. However, the total number of interactions gained is far lower than those lost, with a maximum gain of 30-50 interactions at the elevation with the highest gain, depending on climate scenario.

As species ranges shift, this also results in novel co-occurrences among species that have never been observed together before, so we are unsure if they are capable of interacting. Maps of the number of novel co-occurrences are shown in Supplemental Figure S4, which are primarily concentrated in the eastern foothills and subalpine, and typically are far lower than the number of lost interactions, although the highest 20% quantile covers 30-200 novel co-occurrences, which are similar in number across all climate scenarios.

#figure(
  image("../plots/interaction_loss.png"),
  caption: [The total number of lost interactions at the end of this century for each climate scenario. Each shade of purple represents a 20% quantile of lost interactions in the most extreme scenario, with the cutoffs between quantiles labeled on the color bar. The bar plot in the bottom right of each map is the proportion of area that falls into each quantile. The background (regions in white) have an expected loss of 0 interactions (and in much of this region, there are 0 interactions in the baseline to begin with). _Bottom Right_: the mean number of lost interactions at each elevation in each of the climate scenarios (colors).]
) <interaction-loss>

=== Shifting range overlap among interacting species

In @rewiring, we illustrate the distribution of the relative range overlap between each bumble bee species and the plants they pollinate under the moderate warming scenario (SSP 2-4.5) across each future time-period. While there is a general decline in the median overlap for each bumble bee species, the distributions highlight the considerable variation across the diverse plant communities each bee interacts with. 

To summarize these shifts, we calculate the median range overlap for each focal species $s$ across all of its interaction partners, yielding a single value for each species per time-period. We present this aggregated data from two perspectives in @rewiring (right): the _bee perspective_ (top), where the distribution represents the median overlap across the bee species pool, and the _plant perspective_, where the distribution is the median overlap across all plant species. 

Both perspectives show a consistent slight increase in overlap during the earliest time-period (2021-2040), with subsequent divergence in outcomes depending on climate scenarios. Under moderate and extreme climate scenarios (SSP 2-4.5 and 3-7.0) there is marked decline in range overlaps, whereas the mild warming scenario (SSP 1-2.6) shows relative stability. Specifically, from the bee perspective, the decline is particularly pronounced, with a 25% decline in range overlap by 2100 under SSP 2-4.5, and a 40% decline by 2100 under SSP 3-7.0.

From the plant perspective, while the general trend still matches this pattern of decline in moderate and extreme climate scenarios, the distribution is characterized by a considerable number of outlier plant species, all on the upper end of increasing overlap. This corresponds to species “moving in” to the system at high levels as their range expands into the southern Rocky Mountains. For example, _Ipomopsis aggregata_ already has a widespread range, but is projected to make large range gains in the northwest arid plains, along with many bee species @range-shift. _Taraxacum officinale_, the common dandelion, is naturalized in temperate climates of North America, and expected to gain much range in the western part of the extent in the high-elevation arid grasslands. 

Notably, species within the genus _Asclepias_ (milkweeds) ---  _A. tuberosa_, _A. asperula_, and _A. speciosa_ --- consistently exhibit the highest gain in range overlap with their interaction partners across time-periods and climate scenarios. Asclepias tuberrosa has limited distribution in the Front Range, but is widespread in the southwestern United States, including the south west of the region of interest, and is projected to gain considerable range in the southwestern foothills and at higher elevations in the east. _Asclepias asperula_ is already widespread in the south and expected to move northward. 

Despite the general trend of overlap decline, this variation points to a common feature of ecosystem response to climate change, which is substantial variation in the trajectories of individual species, producing distinct “winners” and “losers”.

#figure(
  image("../plots/overlap_change.png"),
  caption: [ (*A*) Density plots for the relative range overlap size for each plant species a given bee interacts with. Each panel corresponds to a future time-period, all under the middle-of-the-road climate scenario (SSP 2-4.5). (*B*) Box-and-whisker plots depicting the median amount of range overlap for interacting species across different future time-periods (columns) and climate scenarios (colors), relative to the baseline. The top panel shows bee species, and the bottom shows plant species. In the plant panel, points depict outliers that are more than $1.5cal(R)$ from the edge of each box, where $cal(R)$ is the inter-quantile range, i.e. the difference between the 75% and 25% quantiles. Images for _A. asperula_ and _A. tuberosa_ are Creative Commons licensed and come from Wikipedia users Eric Hunt and Lunch, respectively.]
) <rewiring>

== Winning and losing species 

We classify species as relative or absolute winners and losers based on changes in both total range area and median spatial overlap with their interaction partners. Absolute winners gain range area and also increase their median overlap with interacting species. Relative winners lose range area but still experience an increase in median overlap. Absolute losers lose both range area and median overlap, while relative losers gain range area but show a decrease in median overlap with interaction partners. @winners-and-losers shows the number of winning and losing species across time periods and climate scenarios. There a very few relative losers as relative range size change and relative overlap are positively correlated — the average Spearman correlation across scenarios and time-periods is $rho = 0.76$ — see Supplemental Figure S5.

Notably in @winners-and-losers, the number of winners and losers is stable in the mild climate warming scenario, but we see a large increase in absolute loser bees (up to more than half of them) in moderate warming, and still further increase to 10/13 bees as absolute losers at the end of the century under SSP 3-7.0. We see a similar increase under more severe warming scenarios for plants as well, but the increase is less drastic than the jump for bees when shifting from mild to moderate warming.


#figure(
  image("../plots/sankey.png"),
  caption: [Sankey plots depicting the number of species in each of the winner/loser categories (absolute winner in green, relative winner in blue, absolute loser in orange, and relative loser in purple) across time. Each Sankey plot depicts the four future time periods as columns. Bee species are shown in the top, and plant species in the bottom. The number under each vertical bar corresponds to the number of species in the above category. Each panel column corresponds to a climate scenario.]
) <winners-and-losers>


= Discussion 

By combining in-situ interaction data with community occurrence records and raster projections of bioclimatic variables, we are able to predict the contemporary ranges of the _Bombus_ species in the pollination metaweb, and project the future range shifts of each species, and quantify the degree of spatial rewiring that this network will face over the remainder of the 21st century under different climate scenarios. We found consistent predicted upward elevational range shifts under all scenarios, but with shifts being contained to around 150-250 meters upward by 2021-2040 under SSP 1-2.6, while suitable ranges continued to move further upward over the rest of the century under more extreme warming scenarios. We identified the montane region (2500-3000m elevation) of the southern Rocky Mountains as a hotspot for interaction loss, with nearly an order of magnitude more interactions expected to be lost than gained in the locations with the most extreme change, suggesting vertical disassembly of this network may not be compensated by colonization by new species. The projected decline in median range overlap poses a significant threat to the robustness of these networks. Under both moderate and extreme warming scenarios there is considerable expected decline in the size of median range overlap by the end of the century (30-40% in SSP 3-7.0) from the perspective of both bumble bees and the plants they pollinate. While some species emerge as climate “winners”, the proportion of winners declines with increasing warming.

It is essential to remember these projections are based on suitability based on bioclimatic variables, which are not, alone, the determinant of future distribution and abundance of species  @Thomas2010ClimateClimate @Lawlor2024MechanismsDetection. There are numerous factors that are required for species to track their suitable climatic conditions. There are abiotic effects not directly accounted for here: for example, the availability of oxygen (for bees) and carbon dioxide (for plants) is not directly considered in bioclimatic variables, and species may have physiological requirements that cannot be met where the climatic conditions of temperature and precipitation are most suitable @Jacobsen2020DilemmaAltitudinal. Additionally, high elevations are subject to more extreme winds, and the potential for frost, which both could damage plants and inhibit their reproduction @Steltzer2009BiologicalConsequences. This is compounded by the impact of habitat cover, which in some montane or subalpine areas may be too densely forested for bumble bee foraging and nesting. 

Further, biotic effects also impact the ability of species to track their ranges. It is thought that the relative sparsity of pollinators at high altitudes plant reproduction in alpine environments @Totland1993PollinationAlpine, although the more intense winds found at higher altitudes can substitute for animal pollination in some species @Totland2001PollenLimitation. There is also the impact of the limited dispersal capacity for some insects — @Pyke2016EffectsClimate found upward shifts in the same system (bumble bees at RMBL field sites), but not enough to track the average temperature of their range 30 years prior @Pyke1982LocalGeographic. Similarly, mismatches between bees and their plant pollination parents could result in decoupling, e.g. as bees are able to move to higher elevations faster than plants with slower lifecycles or less capacity for upward dispersal. The reshuffling of ranges also will affect interactions besides plant-pollinator mutualisms: competition with newly arriving species has the potential to disrupt existing community structure. It is also expected that increased upward movement of bumble bees will lead to increased competition among bees @Barthell2025BumbleBee. Even in the absence of clear competitive advantages for some species, the ability of species to invade (or resist invasion) may be contingent on the order of arrival of species, as priority effects are the primary factor in community assembly @Song2021UntanglingComplexity @Thompson2017DispersalGoverns. Here we have modeled bee and plant distributions independently, but accounting for the role interactions play in facilitating or limiting range shifts will be crucial future work to better understand the full picture of spatial rewiring.

Therefore, our results predicting species and interaction richness into the future represent a “best-case” where species are capable of perfectly tracking their suitable climatic niches across space and elevation. Rather than treating these as definitive forecasts of plant-pollinator network change, we believe these results provide guidelines for prioritizing further research into what species and particular interactions are expected to undergo the most change, and what the impact of this change on species diversity and persistence will be. For example, these projections identify which and where pairs of species are expected to co-occur for the first time, which provides both a list of species with which to use models to predict if pollination interactions between these species are biologically feasible @Strydom2021RoadmapPredicting, but also spatial locations to target sampling to validate these predictions. This is essential to meet the guidelines from the International Panel on Biodiversity and Ecosystem Services (IPBES), which highlights mapping pollination as one of the necessary directions for addressing knowledge gaps in our understanding of plant-pollinator systems @Potts2016AssessmentReport.

Experiments are necessary to confidently assess the ecological consequences of projected changes in network composition on species diversity @HilleRisLambers2013HowWill, but manipulating the full scope of all possible changes in these systems would be impractical. Therefore, the framework presented here can provide projected impacts that can guide these experiments toward testing the consequences of the changes that are most likely to be realized in the real world. Future work may focus on developing mechanistic species distribution models to directly incorporate species physiological limits into range shift projections, but these models require physiological data that is not widely available as it is difficult to collect, and thus benefit from work like this to prioritize data collection on species' physiological response to expected change.

We have demonstrated how species distribution modelling can be combined with in-situ interaction surveys to generate spatially explicit projections of network structure to map the rewiring of plant-pollinator networks. Developing a spatiotemporally explicit theory of species interaction networks is essential for understanding and mitigating the consequences of climate change on these systems and the services they provide people @Strydom2021RoadmapPredicting. In addition to guidance for future experimentation, spatially explicit projections of network composition and change can guide where future monitoring efforts will be most fruitful, such that they can provide the most information possible to detect and attribute change @Gonzalez2023FrameworkDetection, and make better decisions to manage and mitigate the negative consequences of this change in these systems @Chapman2023BridgingAdaptive. This work is essential to guide future long-term monitoring programs of plant-pollinator interactions, which can then collect data for shorter-term forecasts to better enable adaptive management and conservation @Dietze2018IterativeNearterm. Together, this would enable multi-scale prediction of the biogeography  of species interaction network composition (as done here). These predictions combined process-based models of the dynamics of abundance in plant-pollinator communities @Valdovinos2019MutualisticNetworks, would serve to aid both conservation and better scientific understanding of the ecology and evolution of plant-pollinator interactions, under climate change.


---

*Code and Data Availability*: Source code for the analysis can be found in #text(fill: blue)[#link("https://github.com/gottacatchenall/ColoradoBumblebees", "this")] Github repository. TK Zenodo.

*Acknowledgements*:  MDC is funded by an IVADO Postdoctoral Fellowship. TP is funded by an NSERC Discovery grant, a Discovery Acceleration Supplement grant, and a Wellcome Trust grant (223764/Z/21/Z). AG and MDC were supported by the Liber Ero Chair in Conservation. 

// #showbibliography("refs.bib") 
#bibliography("refs.bib", title: "References", style: "springer-basic-author-date")


